CREATE TABLE country (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    iso_code      VARCHAR(2)   NOT NULL UNIQUE,
    currency_code VARCHAR(3)   NOT NULL
);

CREATE TABLE department (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE employee (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code      VARCHAR(20)  NOT NULL UNIQUE,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    email              VARCHAR(255) NOT NULL UNIQUE,
    department_id      BIGINT       NOT NULL REFERENCES department (id),
    country_id         BIGINT       NOT NULL REFERENCES country (id),
    job_title          VARCHAR(150) NOT NULL,
    hire_date          DATE         NOT NULL,
    employment_status  VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_employee_department ON employee (department_id);
CREATE INDEX idx_employee_country ON employee (country_id);
CREATE INDEX idx_employee_status ON employee (employment_status);

CREATE TABLE compensation_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT         NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    amount          NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    currency_code   VARCHAR(3)     NOT NULL,
    effective_date  DATE           NOT NULL,
    reason          VARCHAR(20)    NOT NULL,
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_compensation_employee ON compensation_record (employee_id);
CREATE INDEX idx_compensation_employee_effective ON compensation_record (employee_id, effective_date DESC);

CREATE TABLE exchange_rate (
    currency_code VARCHAR(3)      NOT NULL PRIMARY KEY,
    rate_to_usd   NUMERIC(18, 8)  NOT NULL CHECK (rate_to_usd > 0)
);
